# Generated by Django 5.0.2 on 2024-02-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPLMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("city", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("team1", models.CharField(max_length=255)),
                ("team2", models.CharField(max_length=255)),
                ("toss_winner", models.CharField(max_length=255)),
                ("toss_decision", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=255)),
                ("dl_applied", models.BooleanField()),
                ("winner", models.CharField(max_length=255)),
                ("win_by_runs", models.IntegerField()),
                ("win_by_wickets", models.IntegerField()),
                ("player_of_match", models.CharField(max_length=255)),
                ("venue", models.CharField(max_length=255)),
                ("umpire1", models.CharField(max_length=255)),
                ("umpire2", models.CharField(max_length=255)),
                ("umpire3", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="IPLDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.IntegerField()),
                ("batting_team", models.CharField(max_length=255)),
                ("bowling_team", models.CharField(max_length=255)),
                ("over", models.IntegerField()),
                ("ball", models.IntegerField()),
                ("batsman", models.CharField(max_length=255)),
                ("non_striker", models.CharField(max_length=255)),
                ("bowler", models.CharField(max_length=255)),
                ("is_super_over", models.BooleanField()),
                ("wide_runs", models.IntegerField()),
                ("bye_runs", models.IntegerField()),
                ("legbye_runs", models.IntegerField()),
                ("noball_runs", models.IntegerField()),
                ("penalty_runs", models.IntegerField()),
                ("batsman_runs", models.IntegerField()),
                ("extra_runs", models.IntegerField()),
                ("total_runs", models.IntegerField()),
                (
                    "player_dismissed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dismissal_kind",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fielder", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iplApp.iplmatch",
                    ),
                ),
            ],
        ),
    ]
